### ISSUE TITLE
[New Data Source]: cluster

### ISSUE THREAD

**Issue by carchi8py** [NetApp/terraform-provider-netapp-ontap#16]
### Description

Currently only the single data source was created with no variables 

Should support

name
password
location
contact
dns_domain
name_servers
ntp_servers
license
configuration_backup
management_interface
nodes
timezone

### Requested Resource(s) and/or Data Source(s)

netapp_ontap_cluster_data_source

### References

https://library.netapp.com/ecmdocs/ECMLP2885799/html/#/cluster/cluster_get

### Would you like to implement a fix?

None

**Comment by wenjun666** [comment]
"The field named \"license\" is not supported for \"fields\" on GET because it is not a readable attribute."
"The field named \"configuration_backup\" is not supported for \"fields\" on GET because it is not a readable attribute."
"The field named \"management_interface\" is not supported for \"fields\" on GET because it is not a readable attribute."
